// <auto-generated />
using ArabianCo.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;

#nullable disable

namespace ArabianCo.Migrations
{
    [DbContext(typeof(ArabianCoDbContext))]
    [Migration("20250901102923_AddPhoneAndMakeEmailOptional")]
    partial class AddPhoneAndMakeEmailOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This method is intentionally left empty. The full model snapshot is maintained in ArabianCoDbContextModelSnapshot.
        }
    }
}
